#!/bin/bash
# setup.sh — one-time SpindleBot setup (safe to re-run)
#
# What this does:
#   1. Creates ~/.config/spindlebot/
#   2. Copies config/secrets example files if they don't already exist
#   3. Writes ~/.config/spindlebot/bootstrap.sh (pipeline dir baked in)
#   4. Installs tomli if Python < 3.11 (needed before config loads)
#   5. Migrates legacy ~/Music/Staging + ~/Music/Library into the new
#      Import/Pending working areas (safe + idempotent; never deletes old dirs)
#   6. Installs music-watcher.sh to ~/.local/bin/
#   7. Installs launchd plists to ~/Library/LaunchAgents/
#   8. Runs `python -m spindlebot check` so you can see what needs filling in

set -euo pipefail

PIPELINE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$HOME/.config/spindlebot"
PYTHON="${PYTHON:-/opt/homebrew/bin/python3}"

# Fall back to whatever python3 is on PATH
if [ ! -x "$PYTHON" ]; then
  PYTHON="$(command -v python3 2>/dev/null || true)"
fi
if [ -z "$PYTHON" ]; then
  echo "ERROR: python3 not found. Install via Homebrew: brew install python3" >&2
  exit 1
fi

echo "SpindleBot setup"
echo "  Pipeline dir : $PIPELINE_DIR"
echo "  Config dir   : $CONFIG_DIR"
echo "  Python       : $PYTHON ($("$PYTHON" --version))"
echo ""

# ── 1. Config directory ───────────────────────────────────────────────────────
mkdir -p "$CONFIG_DIR"

# ── 2. Copy example files if absent ──────────────────────────────────────────
if [ ! -f "$CONFIG_DIR/config.toml" ]; then
  cp "$PIPELINE_DIR/config.toml.example" "$CONFIG_DIR/config.toml"
  echo "Created $CONFIG_DIR/config.toml — edit it before running the pipeline."
else
  echo "config.toml already exists — skipping."
fi

if [ ! -f "$CONFIG_DIR/secrets.toml" ]; then
  cp "$PIPELINE_DIR/secrets.toml.example" "$CONFIG_DIR/secrets.toml"
  chmod 600 "$CONFIG_DIR/secrets.toml"
  echo "Created $CONFIG_DIR/secrets.toml — fill in your credentials."
else
  echo "secrets.toml already exists — skipping."
fi

# ── 3. Write bootstrap.sh (pipeline dir is baked in here) ────────────────────
cat > "$CONFIG_DIR/bootstrap.sh" << BOOTSTRAP
#!/bin/bash
# Auto-generated by setup.sh — do not edit by hand.
# Re-run setup.sh if you move the pipeline directory.

_SPINDLEBOT_PYTHON="${PYTHON}"
_SPINDLEBOT_PIPELINE_DIR="${PIPELINE_DIR}"

eval "\$(PYTHONPATH="\$_SPINDLEBOT_PIPELINE_DIR" "\$_SPINDLEBOT_PYTHON" -m spindlebot config shell 2>&1)" || {
  echo "ERROR: SpindleBot config failed. Check ~/.config/spindlebot/config.toml" >&2
  return 1
}
BOOTSTRAP
chmod +x "$CONFIG_DIR/bootstrap.sh"
echo "Wrote $CONFIG_DIR/bootstrap.sh"

# ── 4. Install tomli if needed (Python < 3.11) ───────────────────────────────
# MUST run before any `python -m spindlebot ...` below: config loading imports
# tomllib, which is stdlib only on 3.11+. Without tomli on older Python,
# resolve_cfg would fail silently and the migrate + mkdir steps would no-op,
# leaving `spindlebot check` failing on a fresh setup.
# Numeric version test via Python's exit code — a shell string compare like
# `"(3, 9)" < "(3, 11)"` sorts lexicographically and would wrongly skip tomli
# on 3.8/3.9.
if ! "$PYTHON" -c "import sys; sys.exit(0 if sys.version_info >= (3, 11) else 1)"; then
  if ! "$PYTHON" -c "import tomli" 2>/dev/null; then
    echo "Installing tomli for Python < 3.11..."
    "$PYTHON" -m pip install tomli --quiet --break-system-packages
  fi
fi

# ── 5. Migrate legacy working dirs + ensure the working areas exist ──────────
# Safe + idempotent: creates the new dirs, relocates any contents out of the old
# default locations, reconciles beets DB paths for the moved Pending area, and
# never deletes the old top-level dirs. Logic lives in a sourceable lib so it is
# unit-tested in tests/shell/test_migrate_work_dirs.bats.
resolve_cfg() { PYTHONPATH="$PIPELINE_DIR" "$PYTHON" -m spindlebot config get "$1" 2>/dev/null || true; }

# shellcheck source=migrate-work-dirs.sh
source "$PIPELINE_DIR/migrate-work-dirs.sh"
migrate_work_dirs \
  "$(resolve_cfg core.import_dir)" \
  "$(resolve_cfg core.pending_dir)" \
  "$(resolve_cfg tools.beets_db)" \
  "$HOME/Music/Staging" \
  "$HOME/Music/Library"

# Processing + Archive have no legacy dir to migrate — just ensure they exist so
# `spindlebot check` passes on a fresh setup. (Archive's prior default was
# ~/Music/All Discs; that old location is intentionally NOT auto-migrated.)
PROCESSING_DIR="$(resolve_cfg core.processing_dir)"
[ -n "$PROCESSING_DIR" ] && mkdir -p "$PROCESSING_DIR"
ARCHIVE_DIR="$(resolve_cfg core.archive_dir)"
[ -n "$ARCHIVE_DIR" ] && mkdir -p "$ARCHIVE_DIR"

# ── 6. Install music-watcher.sh ───────────────────────────────────────────────
mkdir -p "$HOME/.local/bin"
cp "$PIPELINE_DIR/music-watcher.sh" "$HOME/.local/bin/music-watcher.sh"
chmod +x "$HOME/.local/bin/music-watcher.sh"
echo "Installed music-watcher.sh → ~/.local/bin/music-watcher.sh"

# ── 7. Generate + install launchd agents ─────────────────────────────────────
# The plists are GENERATED (not copied) so the per-machine bits — home dir, log
# dir, and the retention volume to watch — are correct for THIS install rather
# than baked to one person's machine. The watch volume comes from the first
# enabled local_drive [[destinations]] (config, not a hard-coded drive).
LAUNCH_AGENTS="$HOME/Library/LaunchAgents"
mkdir -p "$LAUNCH_AGENTS"

# Pull the computed environment (log dir + retention watch volume) for THIS host.
# shellcheck source=/dev/null
source "$CONFIG_DIR/bootstrap.sh" 2>/dev/null || true
LOG_DIR="${SPINDLEBOT_LOG_DIR:-$HOME/.config/beets}"
WATCH_VOLUME="${SPINDLEBOT_WATCH_VOLUME:-}"

# launchd refuses to load an agent whose StandardOut/ErrorPath parent doesn't
# exist — make sure the log dir is there before we bootstrap the agents.
mkdir -p "$LOG_DIR"

cat > "$LAUNCH_AGENTS/com.strangestlens.music-watcher.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.strangestlens.music-watcher</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>$HOME/.local/bin/music-watcher.sh</string>
  </array>
  <key>StandardOutPath</key>
  <string>$LOG_DIR/watcher-stdout.log</string>
  <key>StandardErrorPath</key>
  <string>$LOG_DIR/watcher-stderr.log</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
</dict>
</plist>
PLIST
echo "Generated com.strangestlens.music-watcher.plist"

# WatchPaths fires the sync agent when the retention volume mounts. With no
# local_drive destination configured yet, install it without a trigger (still
# runnable manually / by `spindlebot restart`).
if [ -n "$WATCH_VOLUME" ]; then
  WATCH_BLOCK="  <key>WatchPaths</key>
  <array>
    <string>$WATCH_VOLUME</string>
  </array>"
else
  WATCH_BLOCK="  <!-- No local_drive destination configured — no mount trigger. -->"
  echo "  (no local_drive destination — sync agent installed without a mount trigger)"
fi

cat > "$LAUNCH_AGENTS/com.strangestlens.music-sync.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.strangestlens.music-sync</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>$PIPELINE_DIR/music-sync.sh</string>
  </array>
$WATCH_BLOCK
  <key>StandardOutPath</key>
  <string>$LOG_DIR/music-sync-stdout.log</string>
  <key>StandardErrorPath</key>
  <string>$LOG_DIR/music-sync-stderr.log</string>
  <key>RunAtLoad</key>
  <false/>
</dict>
</plist>
PLIST
echo "Generated com.strangestlens.music-sync.plist"

GUI_UID="gui/$(id -u)"

# Retire the pre-rename sync agent if it's still loaded/installed (music-sync-rugged).
launchctl bootout "$GUI_UID/com.strangestlens.music-sync-rugged" 2>/dev/null || true
rm -f "$LAUNCH_AGENTS/com.strangestlens.music-sync-rugged.plist"

# Validate + (re)load. bootout is a no-op if not currently loaded.
for label in \
  com.strangestlens.music-watcher \
  com.strangestlens.music-sync; do
  if ! plutil -lint "$LAUNCH_AGENTS/$label.plist" >/dev/null; then
    echo "ERROR: generated $label.plist is invalid" >&2
    exit 1
  fi
  launchctl bootout "$GUI_UID/$label" 2>/dev/null || true
  launchctl bootstrap "$GUI_UID" "$LAUNCH_AGENTS/$label.plist"
  echo "Started $label"
done

# ── 8. Validate ────────────────────────────────────────────────────────────────
echo ""
echo "Running validation..."
PYTHONPATH="$PIPELINE_DIR" "$PYTHON" -m spindlebot check
echo ""
echo "Done. Next steps:"
echo "  1. Edit $CONFIG_DIR/config.toml   — paths for your machine"
echo "  2. Edit $CONFIG_DIR/secrets.toml  — Telegram token, Genius API key"
echo "  3. Run: python -m spindlebot check  (from $PIPELINE_DIR)"
