#!/bin/bash
# setup.sh — one-time SpindleBot setup (safe to re-run)
#
# What this does:
#   1. Creates ~/.config/spindlebot/
#   2. Copies config/secrets example files if they don't already exist
#   3. Writes ~/.config/spindlebot/bootstrap.sh (pipeline dir baked in)
#   4. Installs tomli if Python < 3.11
#   5. Runs `python -m spindlebot check` so you can see what needs filling in

set -euo pipefail

PIPELINE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$HOME/.config/spindlebot"
PYTHON="${PYTHON:-/opt/homebrew/bin/python3}"

# Fall back to whatever python3 is on PATH
if [ ! -x "$PYTHON" ]; then
  PYTHON="$(command -v python3 2>/dev/null || true)"
fi
if [ -z "$PYTHON" ]; then
  echo "ERROR: python3 not found. Install via Homebrew: brew install python3" >&2
  exit 1
fi

echo "SpindleBot setup"
echo "  Pipeline dir : $PIPELINE_DIR"
echo "  Config dir   : $CONFIG_DIR"
echo "  Python       : $PYTHON ($("$PYTHON" --version))"
echo ""

# ── 1. Config directory ───────────────────────────────────────────────────────
mkdir -p "$CONFIG_DIR"

# ── 2. Copy example files if absent ──────────────────────────────────────────
if [ ! -f "$CONFIG_DIR/config.toml" ]; then
  cp "$PIPELINE_DIR/config.toml.example" "$CONFIG_DIR/config.toml"
  echo "Created $CONFIG_DIR/config.toml — edit it before running the pipeline."
else
  echo "config.toml already exists — skipping."
fi

if [ ! -f "$CONFIG_DIR/secrets.toml" ]; then
  cp "$PIPELINE_DIR/secrets.toml.example" "$CONFIG_DIR/secrets.toml"
  chmod 600 "$CONFIG_DIR/secrets.toml"
  echo "Created $CONFIG_DIR/secrets.toml — fill in your credentials."
else
  echo "secrets.toml already exists — skipping."
fi

# ── 3. Write bootstrap.sh (pipeline dir is baked in here) ────────────────────
cat > "$CONFIG_DIR/bootstrap.sh" << BOOTSTRAP
#!/bin/bash
# Auto-generated by setup.sh — do not edit by hand.
# Re-run setup.sh if you move the pipeline directory.

_SPINDLEBOT_PYTHON="${PYTHON}"
_SPINDLEBOT_PIPELINE_DIR="${PIPELINE_DIR}"

eval "\$(PYTHONPATH="\$_SPINDLEBOT_PIPELINE_DIR" "\$_SPINDLEBOT_PYTHON" -m spindlebot config shell 2>&1)" || {
  echo "ERROR: SpindleBot config failed. Check ~/.config/spindlebot/config.toml" >&2
  return 1
}
BOOTSTRAP
chmod +x "$CONFIG_DIR/bootstrap.sh"
echo "Wrote $CONFIG_DIR/bootstrap.sh"

# ── 4. Install tomli if needed ────────────────────────────────────────────────
PY_VERSION=$("$PYTHON" -c "import sys; print(sys.version_info[:2])")
if [[ "$PY_VERSION" < "(3, 11)" ]]; then
  if ! "$PYTHON" -c "import tomli" 2>/dev/null; then
    echo "Installing tomli for Python < 3.11..."
    "$PYTHON" -m pip install tomli --quiet --break-system-packages
  fi
fi

# ── 5. Validate ────────────────────────────────────────────────────────────────
echo ""
echo "Running validation..."
PYTHONPATH="$PIPELINE_DIR" "$PYTHON" -m spindlebot check
echo ""
echo "Done. Next steps:"
echo "  1. Edit $CONFIG_DIR/config.toml   — paths for your machine"
echo "  2. Edit $CONFIG_DIR/secrets.toml  — Telegram token, Genius API key"
echo "  3. Run: python -m spindlebot check  (from $PIPELINE_DIR)"
