#!/bin/bash
# setup.sh — one-time SpindleBot setup (safe to re-run)
#
# What this does:
#   1. Creates ~/.config/spindlebot/
#   2. Copies config/secrets example files if they don't already exist
#   3. Writes ~/.config/spindlebot/bootstrap.sh (pipeline dir baked in)
#   4. Migrates legacy ~/Music/Staging + ~/Music/Library into the new
#      Import/Pending working areas (safe + idempotent; never deletes old dirs)
#   5. Installs tomli if Python < 3.11
#   6. Installs music-watcher.sh to ~/.local/bin/
#   7. Installs launchd plists to ~/Library/LaunchAgents/
#   8. Runs `python -m spindlebot check` so you can see what needs filling in

set -euo pipefail

PIPELINE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$HOME/.config/spindlebot"
PYTHON="${PYTHON:-/opt/homebrew/bin/python3}"

# Fall back to whatever python3 is on PATH
if [ ! -x "$PYTHON" ]; then
  PYTHON="$(command -v python3 2>/dev/null || true)"
fi
if [ -z "$PYTHON" ]; then
  echo "ERROR: python3 not found. Install via Homebrew: brew install python3" >&2
  exit 1
fi

echo "SpindleBot setup"
echo "  Pipeline dir : $PIPELINE_DIR"
echo "  Config dir   : $CONFIG_DIR"
echo "  Python       : $PYTHON ($("$PYTHON" --version))"
echo ""

# ── 1. Config directory ───────────────────────────────────────────────────────
mkdir -p "$CONFIG_DIR"

# ── 2. Copy example files if absent ──────────────────────────────────────────
if [ ! -f "$CONFIG_DIR/config.toml" ]; then
  cp "$PIPELINE_DIR/config.toml.example" "$CONFIG_DIR/config.toml"
  echo "Created $CONFIG_DIR/config.toml — edit it before running the pipeline."
else
  echo "config.toml already exists — skipping."
fi

if [ ! -f "$CONFIG_DIR/secrets.toml" ]; then
  cp "$PIPELINE_DIR/secrets.toml.example" "$CONFIG_DIR/secrets.toml"
  chmod 600 "$CONFIG_DIR/secrets.toml"
  echo "Created $CONFIG_DIR/secrets.toml — fill in your credentials."
else
  echo "secrets.toml already exists — skipping."
fi

# ── 3. Write bootstrap.sh (pipeline dir is baked in here) ────────────────────
cat > "$CONFIG_DIR/bootstrap.sh" << BOOTSTRAP
#!/bin/bash
# Auto-generated by setup.sh — do not edit by hand.
# Re-run setup.sh if you move the pipeline directory.

_SPINDLEBOT_PYTHON="${PYTHON}"
_SPINDLEBOT_PIPELINE_DIR="${PIPELINE_DIR}"

eval "\$(PYTHONPATH="\$_SPINDLEBOT_PIPELINE_DIR" "\$_SPINDLEBOT_PYTHON" -m spindlebot config shell 2>&1)" || {
  echo "ERROR: SpindleBot config failed. Check ~/.config/spindlebot/config.toml" >&2
  return 1
}
BOOTSTRAP
chmod +x "$CONFIG_DIR/bootstrap.sh"
echo "Wrote $CONFIG_DIR/bootstrap.sh"

# ── 4. Migrate legacy working dirs into the new Import/Pending areas ──────────
# Safe + idempotent: creates the new dirs, relocates any contents out of the old
# default locations, reconciles beets DB paths for the moved Pending area, and
# never deletes the old top-level dirs.
resolve_cfg() { PYTHONPATH="$PIPELINE_DIR" "$PYTHON" -m spindlebot config get "$1" 2>/dev/null || true; }

NEW_IMPORT="$(resolve_cfg core.import_dir)"
NEW_PENDING="$(resolve_cfg core.pending_dir)"
BEETS_DB="$(resolve_cfg tools.beets_db)"
LEGACY_IMPORT="$HOME/Music/Staging"
LEGACY_PENDING="$HOME/Music/Library"

[ -n "$NEW_IMPORT" ] && mkdir -p "$NEW_IMPORT"
[ -n "$NEW_PENDING" ] && mkdir -p "$NEW_PENDING"

# move_contents FROM TO — relocates entries (incl. dotfiles) without clobbering TO.
# Returns 0 only if it actually moved something.
move_contents() {
  local from="$1" to="$2"
  [ -z "$to" ] && return 1
  [ "$from" = "$to" ] && return 1
  [ ! -d "$from" ] && return 1
  [ -z "$(ls -A "$from" 2>/dev/null)" ] && return 1
  echo "Migrating contents: $from → $to"
  mkdir -p "$to"
  ( shopt -s dotglob nullglob; mv "$from"/* "$to"/ 2>/dev/null ) \
    || rsync -a --remove-source-files "$from"/ "$to"/
  return 0
}

move_contents "$LEGACY_IMPORT" "$NEW_IMPORT" || true

if move_contents "$LEGACY_PENDING" "$NEW_PENDING"; then
  # Reconcile beets DB paths for items that lived under the old pending dir.
  if [ -n "$BEETS_DB" ] && [ -f "$BEETS_DB" ] && command -v sqlite3 >/dev/null 2>&1; then
    if sqlite3 "$BEETS_DB" \
        "UPDATE items SET path = replace(path, '${LEGACY_PENDING}', '${NEW_PENDING}') WHERE path LIKE '${LEGACY_PENDING}/%';"; then
      echo "Reconciled beets DB paths: $LEGACY_PENDING → $NEW_PENDING"
    else
      echo "WARNING: beets DB path reconciliation failed — check manually." >&2
    fi
  fi
fi

# ── 5. Install tomli if needed ────────────────────────────────────────────────
# (done before watcher install so bootstrap.sh is ready when watcher starts)
PY_VERSION=$("$PYTHON" -c "import sys; print(sys.version_info[:2])")
if [[ "$PY_VERSION" < "(3, 11)" ]]; then
  if ! "$PYTHON" -c "import tomli" 2>/dev/null; then
    echo "Installing tomli for Python < 3.11..."
    "$PYTHON" -m pip install tomli --quiet --break-system-packages
  fi
fi

# ── 6. Install music-watcher.sh ───────────────────────────────────────────────
mkdir -p "$HOME/.local/bin"
cp "$PIPELINE_DIR/music-watcher.sh" "$HOME/.local/bin/music-watcher.sh"
chmod +x "$HOME/.local/bin/music-watcher.sh"
echo "Installed music-watcher.sh → ~/.local/bin/music-watcher.sh"

# ── 7. Install launchd plists ─────────────────────────────────────────────────
LAUNCH_AGENTS="$HOME/Library/LaunchAgents"
mkdir -p "$LAUNCH_AGENTS"
for plist in \
  com.strangestlens.music-watcher.plist \
  com.strangestlens.music-sync-rugged.plist; do
  if [ -f "$PIPELINE_DIR/$plist" ]; then
    cp "$PIPELINE_DIR/$plist" "$LAUNCH_AGENTS/$plist"
    echo "Installed $plist → ~/Library/LaunchAgents/"
  fi
done

# Reload agents — bootout is a no-op if not currently loaded
GUI_UID="gui/$(id -u)"
for label in \
  com.strangestlens.music-watcher \
  com.strangestlens.music-sync-rugged; do
  launchctl bootout "$GUI_UID/$label" 2>/dev/null || true
  launchctl bootstrap "$GUI_UID" "$LAUNCH_AGENTS/$label.plist"
  echo "Started $label"
done

# ── 8. Validate ────────────────────────────────────────────────────────────────
echo ""
echo "Running validation..."
PYTHONPATH="$PIPELINE_DIR" "$PYTHON" -m spindlebot check
echo ""
echo "Done. Next steps:"
echo "  1. Edit $CONFIG_DIR/config.toml   — paths for your machine"
echo "  2. Edit $CONFIG_DIR/secrets.toml  — Telegram token, Genius API key"
echo "  3. Run: python -m spindlebot check  (from $PIPELINE_DIR)"
